#!/bin/bash

trash_dir=${HOME}/.Trash/$(date +%Y%m%d%H%M%S)
mkdir -p ${trash_dir}

for item in $@; do
  if $(echo ${item} |grep -Evq "^\-|^\-\-"); then
    file_name=$(basename ${item})
    if $(echo ${file_name} |grep -Evq "^\-|^\-\-"); then
      full_path=$(readlink -f ${item})
      full_dir=$(dirname ${full_path})
      mkdir -p ${trash_dir}${full_dir}
      echo -n "Moving ${item} to ${trash_dir}${full_path}..."
      mv ${item} ${trash_dir}${full_path}
      if [[ $? -eq 0 ]]; then
        echo " Done"
      fi
    fi
  fi
done
